site_name: Bus Message Library
site_description: Bus messages serialization library
site_author: Ingemar Hedvall
copyright: Copyright (c) Ingemar Hedvall 2025
docs_dir: mkdocs
site_dir: docs

repo_url: https://github.com/ihedvall/bus_message_lib
 
theme:
    name: mkdocs
    color_mode: auto
    user_color_mode_toggle: true
    nav_style: dark

nav:
    - Home: index.md
    - Reference: html/index.html
    - About: 
        - about.md
        - about/license.md